/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as IncorporarRouteImport } from './routes/incorporar'
import { Route as SeleccionRouteImport } from './routes/seleccion'
import { Route as TableroRouteImport } from './routes/tablero'
import { Route as ComprobanteFolioRouteImport } from './routes/comprobante.$folio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const IncorporarRoute = IncorporarRouteImport.update({
  id: '/incorporar',
  path: '/incorporar',
  getParentRoute: () => rootRouteImport,
} as any)
const SeleccionRoute = SeleccionRouteImport.update({
  id: '/seleccion',
  path: '/seleccion',
  getParentRoute: () => rootRouteImport,
} as any)
const TableroRoute = TableroRouteImport.update({
  id: '/tablero',
  path: '/tablero',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprobanteFolioRoute = ComprobanteFolioRouteImport.update({
  id: '/comprobante/$folio',
  path: '/comprobante/$folio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/incorporar': typeof IncorporarRoute
  '/seleccion': typeof SeleccionRoute
  '/tablero': typeof TableroRoute
  '/comprobante/$folio': typeof ComprobanteFolioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/incorporar': typeof IncorporarRoute
  '/seleccion': typeof SeleccionRoute
  '/tablero': typeof TableroRoute
  '/comprobante/$folio': typeof ComprobanteFolioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/incorporar': typeof IncorporarRoute
  '/seleccion': typeof SeleccionRoute
  '/tablero': typeof TableroRoute
  '/comprobante/$folio': typeof ComprobanteFolioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/embed'
    | '/incorporar'
    | '/seleccion'
    | '/tablero'
    | '/comprobante/$folio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/embed'
    | '/incorporar'
    | '/seleccion'
    | '/tablero'
    | '/comprobante/$folio'
  id:
    | '__root__'
    | '/'
    | '/embed'
    | '/incorporar'
    | '/seleccion'
    | '/tablero'
    | '/comprobante/$folio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedRoute: typeof EmbedRoute
  IncorporarRoute: typeof IncorporarRoute
  SeleccionRoute: typeof SeleccionRoute
  TableroRoute: typeof TableroRoute
  ComprobanteFolioRoute: typeof ComprobanteFolioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incorporar': {
      id: '/incorporar'
      path: '/incorporar'
      fullPath: '/incorporar'
      preLoaderRoute: typeof IncorporarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seleccion': {
      id: '/seleccion'
      path: '/seleccion'
      fullPath: '/seleccion'
      preLoaderRoute: typeof SeleccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tablero': {
      id: '/tablero'
      path: '/tablero'
      fullPath: '/tablero'
      preLoaderRoute: typeof TableroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprobante/$folio': {
      id: '/comprobante/$folio'
      path: '/comprobante/$folio'
      fullPath: '/comprobante/$folio'
      preLoaderRoute: typeof ComprobanteFolioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedRoute: EmbedRoute,
  IncorporarRoute: IncorporarRoute,
  SeleccionRoute: SeleccionRoute,
  TableroRoute: TableroRoute,
  ComprobanteFolioRoute: ComprobanteFolioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
